### ISSUE TITLE
Put demo.gif somewhere else

### ISSUE THREAD

**Issue by fakefred** [sdushantha/fontpreview#17]
I have really slow connection to github. As a result, I can only clone the repo at ~15KiBps. A single demo.gif takes up 5.93MB, which is larger than all other files combined (the repo weighs only 21KB after the removal).

Solution: use an image hosting service and embed the image in README.

**Comment by SmartFinn** [comment]
> Solution: use an image hosting service and embed the image in README.

GitHub caches image from external resources and then distributes from own CDN. It seems there is no way to change it.

**Comment by sdushantha** [comment]
@fakefred If you have a slow connection to GitHub, I think it would be best for you to the "install locally" method which means you dont have to clone the repo.

https://github.com/sdushantha/fontpreview#install-it-locally

I would like to keep all the images and media in this repo so that everything is organized. Hope you understand :)
